### ISSUE TITLE
Error Importing

### ISSUE THREAD

**Issue by George-Madeley** [protomaps/protomaps-leaflet#161] opened 2024-07-15 14:05 UTC
I cannot use leafletLayer or import anything from the protomaps-leaflet module as I am constantly getting import errors relating to the import extensions within the module

No default export exists so I cannot use:
```
import protomapsL from "protomaps-leaflet"
```
When I try and import leafletLayer, I get the following error:

ERROR in ~/node_modules/protomaps-leaflet/dist/frontends/static.js 32:0-35
Module not found: Error: Can't resolve '../painter' in '~\node_modules\protomaps-leaflet\dist\frontends'
Did you mean 'painter.js'?
BREAKING CHANGE: The request '../painter' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

This is also repeated for:
- 'symbolizer.js' in 'dist/default_styles',
- '../default_style/style' in 'dist/frontends',
- '../default_style/themes' in '\dist\frontends',
- '../labeler' in 'dist\frontends',
- '../painter' in 'dist\frontends',
- '../view' in 'dist\frontends',
- './tilecache' in 'dist',
- './view' in 'dist',
- './attribute' in 'dist',
- './line' in 'dist',
- './text' in 'dist'

**Comment by claustres** [comment] 2024-07-15 18:02
It's probably a duplicate of https://github.com/protomaps/protomaps-leaflet/issues/158.

**Comment by claustres** [comment] 2024-07-15 18:04
By the way you can "simulate" a default export with everything like this:
`import * as protomapsL from "protomaps-leaflet"`

**Comment by bdon** [comment] 2024-07-16 11:02
We need some way to reproduce your issue, which also depends on if your environment is CommonJS or ES Modules, what bundler you are using, TypeScript, etc. Can you create and share a minimal example?

**Comment by George-Madeley** [comment] 2024-07-16 12:15
Environment: CommonJS,
Bundler: Webpack,
Typescript: 4.7.4,

ts.config:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src", "src/tabs/.tsx"]
}
```

**Comment by bdon** [comment] 2024-07-25 11:32
Can you please try [4.0.0-alpha.0](https://www.npmjs.com/package/protomaps-leaflet/v/4.0.0-alpha.0)

**Comment by bdon** [comment] 2024-07-28 13:51
v4.0.0 has been published - please reopen if you are still having this issue. https://www.npmjs.com/search?q=protomaps-leaflet

**Closed by bdon** 2024-07-28 13:51 UTC
