### ISSUE TITLE
Version 3.1.1 Stops sending range header

### ISSUE THREAD

**Issue by aswarcewicz** [protomaps/protomaps-leaflet#152] opened 2024-05-02 18:33 UTC
I don't know exactly why, but I see that range header was present in requests in version 3.1.0 but after update to 3.1.1 this header has gone

**Comment by bdon** [comment] 2024-05-03 00:06
What is the full URL you are requesting with any query parameters? 

The logic changed for how it automatically detects if it should treat a string as a PMTiles or a ZXY url.

It used to be checking for ending with `.pmtiles`, but now it strips off params like `foo.pmtiles?abc=123`

**Comment by aswarcewicz** [comment] 2024-05-03 17:30
Just GET on /api/map-tiles/map.pmtiles
Without query params

**Comment by bdon** [comment] 2024-05-04 07:17
Does your URL start with `http:` or `https:`?

**Comment by aswarcewicz** [comment] 2024-05-04 12:08
Https

**Comment by bdon** [comment] 2024-05-05 01:27
Can you create a minimal reproduction page?

**Comment by bdon** [comment] 2024-05-08 01:41
What is your complete, exact URL you are fetching from?

**Comment by wginsberg** [comment] 2024-05-08 14:24
I'm fetching from https://pub-5ba95de8cc2f4dada22bfe563b284734.r2.dev/20230918-z12.pmtiles
Not sure if it matters either way but I am proxying the request through localhost in development

**Comment by bdon** [comment] 2024-05-08 14:30
Yes, how are you specifying the URL passed to `leafletLayer`? Because the form of that string needs to be checked to determine whether it's a ZXY URL or a .pmtiles URL.

**Comment by wginsberg** [comment] 2024-05-08 15:21
The URL being passed to leaflet layer was `/proxy/20230918-z12.pmtiles`.
I'm seeing now that `http://localhost:3000/proxy/20230918-z12.pmtiles` does work 🎊

**Comment by bdon** [comment] 2024-05-09 02:46
It should be fixed in v3.1.2, can you please check?

**Comment by wginsberg** [comment] 2024-05-09 15:16
@bdon looks like both work with 3.1.2 👍

**Comment by bdon** [comment] 2024-05-10 06:44
Thanks for checking, closing!

**Closed by bdon** 2024-05-10 06:44 UTC
